1_StudentDetalisView:
CREATE VIEW StudentDetailsView AS
SELECT * FROM STUDENT
JOIN EDUCATION ON STUDENT.StudentID = EDUCATION.StudentID
JOIN EXPERIENCE ON STUDENT.StudentID = EXPERIENCE.StudentID;

2_ProjectsWithApplicantsView:
CREATE VIEW ProjectsWithApplicantsView AS
SELECT PROJECT.*, COUNT(APPLYING.StudentID) AS ApplicantCount
FROM PROJECT
LEFT JOIN APPLYING ON PROJECT.ProjectID = APPLYING.ProjectID
GROUP BY PROJECT.ProjectID;





